nuwa: overlay: use hardcoded values instead of references
Supposedly using references to different values instead of hardcoded values can cause issues in some ROMs.

java.lang.RuntimeException: Unable to create service com.android.systemui.keyguard.KeyguardService: android.view.InflateException: Binary XML file line #59 in com.android.systemui:layout/super_notification_shade: Binary XML file line #19: You must supply a layout_height attribute., theme={InheritanceMap=[id=0x7f1505c3com.android.systemui:style/Theme.SystemUI, id=0x103042aandroid:style/Theme.DeviceDefault.SystemUI, id=0x1030128android:style/Theme.DeviceDefault, id=0x103042dandroid:style/Theme.DeviceDefaultBase, id=0x1030224android:style/Theme.Material, id=0x1030005android:style/Theme], Themes=[com.android.systemui:style/Theme.SystemUI, forced, android:style/Theme.DeviceDefault.System, forced]}
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5295)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2597)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loopOnce(Looper.java:248)
	at android.os.Looper.loop(Looper.java:338)
	at android.app.ActivityThread.main(ActivityThread.java:9063)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)
Caused by: android.view.InflateException: Binary XML file line #59 in com.android.systemui:layout/super_notification_shade: Binary XML file line #19: You must supply a layout_height attribute., theme={InheritanceMap=[id=0x7f1505c3com.android.systemui:style/Theme.SystemUI, id=0x103042aandroid:style/Theme.DeviceDefault.SystemUI, id=0x1030128android:style/Theme.DeviceDefault, id=0x103042dandroid:style/Theme.DeviceDefaultBase, id=0x1030224android:style/Theme.Material, id=0x1030005android:style/Theme], Themes=[com.android.systemui:style/Theme.SystemUI, forced, android:style/Theme.DeviceDefault.System, forced]}
Caused by: java.lang.UnsupportedOperationException: Binary XML file line #19: You must supply a layout_height attribute., theme={InheritanceMap=[id=0x7f1505c3com.android.systemui:style/Theme.SystemUI, id=0x103042aandroid:style/Theme.DeviceDefault.SystemUI, id=0x1030128android:style/Theme.DeviceDefault, id=0x103042dandroid:style/Theme.DeviceDefaultBase, id=0x1030224android:style/Theme.Material, id=0x1030005android:style/Theme], Themes=[com.android.systemui:style/Theme.SystemUI, forced,